# Generated by Django 3.1.5 on 2021-05-13 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='eventDescription',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='eventTitle',
        ),
    ]
