# Generated by Django 3.1.5 on 2021-05-13 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210512_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='eventDescription',
            new_name='event_description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='eventTitle',
            new_name='event_title',
        ),
    ]
