# Generated by Django 3.1.5 on 2021-05-13 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210512_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='user',
            new_name='event_user',
        ),
    ]
