# Generated by Django 3.1.5 on 2021-05-13 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210512_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.city'),
        ),
    ]
