# Generated by Django 3.1.5 on 2021-05-14 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='name_event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.event'),
        ),
    ]
