# Generated by Django 3.1.5 on 2021-05-14 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_attendance_name_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='num_users',
        ),
    ]
