# Generated by Django 3.1.5 on 2021-05-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_attendance_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='join_event',
            field=models.BooleanField(default=False),
        ),
    ]
