# Generated by Django 3.1.5 on 2021-05-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_attendance_join_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_user_firstName',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='event_user_lastName',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
