# Generated by Django 3.1.5 on 2021-05-19 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210518_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_user_firstName',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_user_lastName',
        ),
    ]
